version: 2
mergeable:
  - when: pull_request.labeled, pull_request.unlabeled, pull_request_review.labeled, pull_request_review.unlabeled, issues.labeled, issues.unlabeled  # can be one or more
    validate:
      # #list of validators. Specify one or more.
    -  do: label
       no_empty:
          enabled: true # Cannot be empty when true.
          #message: 'Needs QA Approval'
       must_include:
          regex: 'QA Approved'
          message: 'Approved by QA team'
       must_exclude:
          regex: 'Need QA'
          message: 'Need be tested by QA'
