version: 2
mergeable:
  - when: pull_request.*, pull_request_review.* #,issues.*  # can be one or more
    validate:
      # #list of validators. Specify one or more.
    -  do: label
       no_empty:
          enabled: true # Cannot be empty when true.
          #message: 'Needs QA Approval'
       must_include:
          regex: 'QA Approved|Skip QA'
          message: 'Approved by QA team'
       must_exclude:
          regex: 'Need QA| QA Rejected '
          message: 'Need be tested by QA'
